// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AlertMessage: typeof import('./src/components/AlertMessage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ForgetPassword: typeof import('./src/components/ForgetPassword.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon.vue')['default']
  }
}

export { }
